name: Run tests

on:  
  push:
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: unit test
      run: |
        pwd
        chmod +x ./test.py
        python ../test.py
      
