name: Run tests

on:  
  push:
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v2
    - name: unit test
      run: |
        echo $pwd
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
        chmod +x ${{ github.workspace }}/test.py
        python ${{ github.workspace }}/test.py
        python -m coverage report
				python -m coverage html
				coverage report -m --fail-under=80
      
