name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main , staging ]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      run : actions/checkout@main

    - name : Install Packages 
      run : pip install coverage
      
    - name: unit test
      run: |
        echo $pwd
        chmod +x ${{ github.workspace }}/test.py
        python ${{ github.workspace }}/test.py
        python -m coverage run -m unittest
        python -m coverage report
        coverage report -m --fail-under=80
