name: Run tests
on:
  push:
    branches: [ main , branch_check ]
  pull_request:
    branches: [ main , staging ,branch_check ]
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
    - name : Checkout code
      run: |
        git clone https://github.com/rishav199812/dindjen.git
        cd dindjen
        git checkout test_branch_check
        
    - name : Install Packages 
      run : pip install coverage
      
    - name: unit test
      run: |
        cd dindjen
        ls -la
        cd coverage
        ls -la
        cd lcov-report
        ls -la
        COVERAGE_FILE="${{ github.workspace }}/coverage/lcov-report/index.html"
        if [ -e "$COVERAGE_FILE" ]; then
          echo "coverage=$(cat $COVERAGE_FILE | grep -A 1 \"class='fl pad1y space-right2'\" | awk 'NR==2' | sed 's/^[^>]*>//;s/<.*$//')" >> "$GITHUB_COV"
          echo "${GITHUB_COV}"
        else
          echo "Error: coverage file not found."
        fi


        
