name: Run tests

on:  
  push:
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: unit test
      run: |
        echo pwd
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE
        chmod +x ${{ github.workspace }}/test.py
        python ${{ github.workspace }}/test.py
      
