name: Run tests

on:  
  push:
  pull_request:
    branches:
      - main

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name : Checkout code
      uses : actions/checkout@v2

    - name : Install Packages 
      run : pip install coverage
      
    - name: unit test
      run: |
        echo $pwd
        chmod +x ${{ github.workspace }}/test.py
        python ${{ github.workspace }}/test.py
        python -m coverage run -m unittest
        python -m coverage report
        coverage report --include='test.py'
